// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4u9HKSXuuaneaFiGZZ9MqjuOQ4TQkJ1M',
    appId: '1:553713560356:web:169f9647a9ad88644521b1',
    messagingSenderId: '553713560356',
    projectId: 'studify-app-54116',
    authDomain: 'studify-app-54116.firebaseapp.com',
    storageBucket: 'studify-app-54116.firebasestorage.app',
    measurementId: 'G-Q41TZBY2F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8bqHlU1Urw16cxEw0WCARzVM2hu36KY',
    appId: '1:553713560356:android:5fe3405f95d6ffe94521b1',
    messagingSenderId: '553713560356',
    projectId: 'studify-app-54116',
    storageBucket: 'studify-app-54116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwTh4UGpreGQ_KX8yvg_KocFT3XKS4iI',
    appId: '1:553713560356:ios:3a13251da238cf3a4521b1',
    messagingSenderId: '553713560356',
    projectId: 'studify-app-54116',
    storageBucket: 'studify-app-54116.firebasestorage.app',
    androidClientId:
        '553713560356-o85erb8tmgli19ecvuqlvsjt7sdmmru8.apps.googleusercontent.com',
    iosClientId:
        '553713560356-udoorvr4smeqrnbcn4fioiit1h2kabbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwTh4UGpreGQ_KX8yvg_KocFT3XKS4iI',
    appId: '1:553713560356:ios:3a13251da238cf3a4521b1',
    messagingSenderId: '553713560356',
    projectId: 'studify-app-54116',
    storageBucket: 'studify-app-54116.firebasestorage.app',
    androidClientId:
        '553713560356-o85erb8tmgli19ecvuqlvsjt7sdmmru8.apps.googleusercontent.com',
    iosClientId:
        '553713560356-udoorvr4smeqrnbcn4fioiit1h2kabbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4u9HKSXuuaneaFiGZZ9MqjuOQ4TQkJ1M',
    appId: '1:553713560356:web:e6ec707a011e3c554521b1',
    messagingSenderId: '553713560356',
    projectId: 'studify-app-54116',
    authDomain: 'studify-app-54116.firebaseapp.com',
    storageBucket: 'studify-app-54116.firebasestorage.app',
    measurementId: 'G-G6PCNFFSLY',
  );
}
